"""
language.py - Multi-Language Support Module for MultiTool
Supports: English, Indonesian, Spanish, German, Chinese, Japanese, Sundanese, Javanese,
          French, Portuguese, Korean, Russian, Arabic, Hindi, Thai, Vietnamese, Turkish, Italian
Default language: English (Global market)

Usage:
    from utils.language import lang, set_language, get_available_languages
    print(lang("greeting"))
    set_language("id")
"""

# ============================================================
# GLOBAL LANGUAGE STATE
# ============================================================
CURRENT_LANGUAGE = "en"

# ============================================================
# LANGUAGE METADATA
# ============================================================
LANGUAGES = {
    "en": {"name": "English", "flag": "🇬🇧", "native": "English"},
    "id": {"name": "Indonesian", "flag": "🇮🇩", "native": "Bahasa Indonesia"},
    "es": {"name": "Spanish", "flag": "🇪🇸", "native": "Español"},
    "de": {"name": "German", "flag": "🇩🇪", "native": "Deutsch"},
    "zh": {"name": "Chinese", "flag": "🇨🇳", "native": "中文"},
    "ja": {"name": "Japanese", "flag": "🇯🇵", "native": "日本語"},
    "su": {"name": "Sundanese", "flag": "🏝️", "native": "Basa Sunda"},
    "jv": {"name": "Javanese", "flag": "🏝️", "native": "Basa Jawa"},
    "fr": {"name": "French", "flag": "🇫🇷", "native": "Français"},
    "pt": {"name": "Portuguese", "flag": "🇧🇷", "native": "Português"},
    "ko": {"name": "Korean", "flag": "🇰🇷", "native": "한국어"},
    "ru": {"name": "Russian", "flag": "🇷🇺", "native": "Русский"},
    "ar": {"name": "Arabic", "flag": "🇸🇦", "native": "العربية"},
    "hi": {"name": "Hindi", "flag": "🇮🇳", "native": "हिन्दी"},
    "th": {"name": "Thai", "flag": "🇹🇭", "native": "ไทย"},
    "vi": {"name": "Vietnamese", "flag": "🇻🇳", "native": "Tiếng Việt"},
    "tr": {"name": "Turkish", "flag": "🇹🇷", "native": "Türkçe"},
    "it": {"name": "Italian", "flag": "🇮🇹", "native": "Italiano"},
}

# ============================================================
# TRANSLATIONS DICTIONARY
# ============================================================
TRANSLATIONS = {
    # ── GREETINGS ──
    "good_morning": {
        "en": "Good Morning",
        "id": "Selamat Pagi",
        "es": "Buenos Días",
        "de": "Guten Morgen",
        "zh": "早上好",
        "ja": "おはようございます",
        "su": "Wilujeng Énjing",
        "jv": "Sugeng Enjang",
        "fr": "Bonjour",
        "pt": "Bom Dia",
        "ko": "좋은 아침",
        "ru": "Доброе утро",
        "ar": "صباح الخير",
        "hi": "सुप्रभात",
        "th": "สวัสดีตอนเช้า",
        "vi": "Chào buổi sáng",
        "tr": "Günaydın",
        "it": "Buongiorno",
    },
    "good_afternoon": {
        "en": "Good Afternoon",
        "id": "Selamat Siang",
        "es": "Buenas Tardes",
        "de": "Guten Tag",
        "zh": "下午好",
        "ja": "こんにちは",
        "su": "Wilujeng Siang",
        "jv": "Sugeng Siang",
        "fr": "Bon Après-midi",
        "pt": "Boa Tarde",
        "ko": "좋은 오후",
        "ru": "Добрый день",
        "ar": "مساء الخير",
        "hi": "शुभ दोपहर",
        "th": "สวัสดีตอนบ่าย",
        "vi": "Chào buổi chiều",
        "tr": "İyi Öğleden Sonra",
        "it": "Buon Pomeriggio",
    },
    "good_evening": {
        "en": "Good Evening",
        "id": "Selamat Sore",
        "es": "Buenas Tardes",
        "de": "Guten Abend",
        "zh": "傍晚好",
        "ja": "こんばんは",
        "su": "Wilujeng Sonten",
        "jv": "Sugeng Sonten",
        "fr": "Bonsoir",
        "pt": "Boa Tarde",
        "ko": "좋은 저녁",
        "ru": "Добрый вечер",
        "ar": "مساء الخير",
        "hi": "शुभ संध्या",
        "th": "สวัสดีตอนเย็น",
        "vi": "Chào buổi tối",
        "tr": "İyi Akşamlar",
        "it": "Buona Sera",
    },
    "good_night": {
        "en": "Good Night",
        "id": "Selamat Malam",
        "es": "Buenas Noches",
        "de": "Gute Nacht",
        "zh": "晚上好",
        "ja": "こんばんは",
        "su": "Wilujeng Wengi",
        "jv": "Sugeng Dalu",
        "fr": "Bonne Nuit",
        "pt": "Boa Noite",
        "ko": "좋은 밤",
        "ru": "Доброй ночи",
        "ar": "تصبح على خير",
        "hi": "शुभ रात्रि",
        "th": "ราตรีสวัสดิ์",
        "vi": "Chúc ngủ ngon",
        "tr": "İyi Geceler",
        "it": "Buona Notte",
    },

    # ── MAIN UI ──
    "welcome": {
        "en": "Welcome to MultiTool",
        "id": "Selamat datang di MultiTool",
        "es": "Bienvenido a MultiTool",
        "de": "Willkommen bei MultiTool",
        "zh": "欢迎使用 MultiTool",
        "ja": "MultiTool へようこそ",
        "su": "Wilujeng Sumping di MultiTool",
        "jv": "Sugeng Rawuh ing MultiTool",
        "fr": "Bienvenue dans MultiTool",
        "pt": "Bem-vindo ao MultiTool",
        "ko": "MultiTool에 오신 것을 환영합니다",
        "ru": "Добро пожаловать в MultiTool",
        "ar": "مرحبًا بك في MultiTool",
        "hi": "MultiTool में आपका स्वागत है",
        "th": "ยินดีต้อนรับสู่ MultiTool",
        "vi": "Chào mừng đến với MultiTool",
        "tr": "MultiTool'a Hoş Geldiniz",
        "it": "Benvenuto in MultiTool",
    },
    "description": {
        "en": "All-in-one utility to simplify your digital life",
        "id": "Program serbaguna untuk mempermudah hidupmu yang ribet",
        "es": "Utilidad todo en uno para simplificar tu vida digital",
        "de": "All-in-One-Tool zur Vereinfachung Ihres digitalen Lebens",
        "zh": "一站式工具，简化您的数字生活",
        "ja": "デジタルライフを簡素化するオールインワンツール",
        "su": "Alat serbaguna pikeun ngagampangkeun kahirupan digital anjeun",
        "jv": "Alat serbaguna kangge nggampangake urip digital sampeyan",
        "fr": "Utilitaire tout-en-un pour simplifier votre vie numérique",
        "pt": "Utilitário completo para simplificar sua vida digital",
        "ko": "디지털 생활을 간소화하는 올인원 유틸리티",
        "ru": "Универсальная утилита для упрощения вашей цифровой жизни",
        "ar": "أداة شاملة لتبسيط حياتك الرقمية",
        "hi": "आपके डिजिटल जीवन को सरल बनाने के लिए ऑल-इन-वन उपयोगिता",
        "th": "ยูทิลิตี้ครบวงจรเพื่อทำให้ชีวิตดิจิทัลของคุณง่ายขึ้น",
        "vi": "Tiện ích tất cả trong một để đơn giản hóa cuộc sống số của bạn",
        "tr": "Dijital hayatınızı basitleştirmek için hepsi bir arada araç",
        "it": "Utilità tutto-in-uno per semplificare la tua vita digitale",
    },
    "status_admin": {
        "en": "Admin (Full Access)",
        "id": "Admin (Akses Penuh)",
        "es": "Admin (Acceso Completo)",
        "de": "Admin (Vollzugriff)",
        "zh": "管理员（完全访问）",
        "ja": "管理者（フルアクセス）",
        "su": "Admin (Aksés Pinuh)",
        "jv": "Admin (Akses Kebak)",
        "fr": "Admin (Accès Complet)",
        "pt": "Admin (Acesso Total)",
        "ko": "관리자 (전체 액세스)",
        "ru": "Админ (Полный доступ)",
        "ar": "مسؤول (وصول كامل)",
        "hi": "एडमिन (पूर्ण पहुँच)",
        "th": "แอดมิน (เข้าถึงเต็มรูปแบบ)",
        "vi": "Admin (Toàn quyền truy cập)",
        "tr": "Yönetici (Tam Erişim)",
        "it": "Admin (Accesso Completo)",
    },
    "status_user": {
        "en": "User (Some Features Limited)",
        "id": "User (Beberapa Fitur Terbatas)",
        "es": "Usuario (Algunas Funciones Limitadas)",
        "de": "Benutzer (Einige Funktionen eingeschränkt)",
        "zh": "用户（部分功能受限）",
        "ja": "ユーザー（一部機能制限あり）",
        "su": "User (Sababaraha Fitur Kawates)",
        "jv": "User (Sawetara Fitur Diwatesi)",
        "fr": "Utilisateur (Certaines fonctions limitées)",
        "pt": "Usuário (Alguns Recursos Limitados)",
        "ko": "사용자 (일부 기능 제한)",
        "ru": "Пользователь (Некоторые функции ограничены)",
        "ar": "مستخدم (بعض الميزات محدودة)",
        "hi": "उपयोगकर्ता (कुछ सुविधाएँ सीमित)",
        "th": "ผู้ใช้ (บางฟีเจอร์ถูกจำกัด)",
        "vi": "Người dùng (Một số tính năng bị giới hạn)",
        "tr": "Kullanıcı (Bazı Özellikler Sınırlı)",
        "it": "Utente (Alcune Funzioni Limitate)",
    },
    "status": {
        "en": "Status",
        "id": "Status",
        "es": "Estado",
        "de": "Status",
        "zh": "状态",
        "ja": "ステータス",
        "su": "Status",
        "jv": "Status",
        "fr": "Statut",
        "pt": "Status",
        "ko": "상태",
        "ru": "Статус",
        "ar": "الحالة",
        "hi": "स्थिति",
        "th": "สถานะ",
        "vi": "Trạng thái",
        "tr": "Durum",
        "it": "Stato",
    },
    "created_by": {
        "en": "Created by",
        "id": "Dibuat oleh",
        "es": "Creado por",
        "de": "Erstellt von",
        "zh": "创建者",
        "ja": "作成者",
        "su": "Dijieun ku",
        "jv": "Digawe dening",
        "fr": "Créé par",
        "pt": "Criado por",
        "ko": "제작자",
        "ru": "Создано",
        "ar": "أنشأه",
        "hi": "द्वारा निर्मित",
        "th": "สร้างโดย",
        "vi": "Tạo bởi",
        "tr": "Oluşturan",
        "it": "Creato da",
    },

    # ── MENU CATEGORIES ──
    "cat_power": {
        "en": "POWER & SYSTEM",
        "id": "POWER dan SYSTEM",
        "es": "ENERGÍA Y SISTEMA",
        "de": "ENERGIE & SYSTEM",
        "zh": "电源与系统",
        "ja": "電源とシステム",
        "su": "DAYA & SISTEM",
        "jv": "DAYA & SISTEM",
        "fr": "ALIMENTATION & SYSTÈME",
        "pt": "ENERGIA & SISTEMA",
        "ko": "전원 및 시스템",
        "ru": "ПИТАНИЕ И СИСТЕМА",
        "ar": "الطاقة والنظام",
        "hi": "पावर और सिस्टम",
        "th": "พลังงานและระบบ",
        "vi": "NGUỒN & HỆ THỐNG",
        "tr": "GÜÇ & SİSTEM",
        "it": "ALIMENTAZIONE & SISTEMA",
    },
    "cat_info": {
        "en": "INFO & MONITORING",
        "id": "INFO dan MONITORING",
        "es": "INFO Y MONITOREO",
        "de": "INFO & ÜBERWACHUNG",
        "zh": "信息与监控",
        "ja": "情報とモニタリング",
        "su": "INFO & MONITORING",
        "jv": "INFO & MONITORING",
        "fr": "INFO & SURVEILLANCE",
        "pt": "INFO & MONITORAMENTO",
        "ko": "정보 및 모니터링",
        "ru": "ИНФОРМАЦИЯ И МОНИТОРИНГ",
        "ar": "المعلومات والمراقبة",
        "hi": "जानकारी और निगरानी",
        "th": "ข้อมูลและการตรวจสอบ",
        "vi": "THÔNG TIN & GIÁM SÁT",
        "tr": "BİLGİ & İZLEME",
        "it": "INFO & MONITORAGGIO",
    },
    "cat_network": {
        "en": "NETWORK & INTERNET",
        "id": "JARINGAN dan INTERNET",
        "es": "RED E INTERNET",
        "de": "NETZWERK & INTERNET",
        "zh": "网络与互联网",
        "ja": "ネットワークとインターネット",
        "su": "JARINGAN & INTERNET",
        "jv": "JARINGAN & INTERNET",
        "fr": "RÉSEAU & INTERNET",
        "pt": "REDE & INTERNET",
        "ko": "네트워크 및 인터넷",
        "ru": "СЕТЬ И ИНТЕРНЕТ",
        "ar": "الشبكة والإنترنت",
        "hi": "नेटवर्क और इंटरनेट",
        "th": "เครือข่ายและอินเทอร์เน็ต",
        "vi": "MẠNG & INTERNET",
        "tr": "AĞ & İNTERNET",
        "it": "RETE & INTERNET",
    },
    "cat_cleanup": {
        "en": "CLEANUP & OPTIMIZATION",
        "id": "PEMBERSIHAN dan OPTIMASI",
        "es": "LIMPIEZA Y OPTIMIZACIÓN",
        "de": "BEREINIGUNG & OPTIMIERUNG",
        "zh": "清理与优化",
        "ja": "クリーンアップと最適化",
        "su": "BERESIH & OPTIMASI",
        "jv": "RESIK & OPTIMASI",
        "fr": "NETTOYAGE & OPTIMISATION",
        "pt": "LIMPEZA & OTIMIZAÇÃO",
        "ko": "정리 및 최적화",
        "ru": "ОЧИСТКА И ОПТИМИЗАЦИЯ",
        "ar": "التنظيف والتحسين",
        "hi": "सफाई और अनुकूलन",
        "th": "ทำความสะอาดและเพิ่มประสิทธิภาพ",
        "vi": "DỌN DẸP & TỐI ƯU",
        "tr": "TEMİZLİK & OPTİMİZASYON",
        "it": "PULIZIA & OTTIMIZZAZIONE",
    },
    "cat_process": {
        "en": "PROCESSES & STARTUP",
        "id": "PROSES dan STARTUP",
        "es": "PROCESOS E INICIO",
        "de": "PROZESSE & AUTOSTART",
        "zh": "进程与启动",
        "ja": "プロセスとスタートアップ",
        "su": "PROSÉS & STARTUP",
        "jv": "PROSES & STARTUP",
        "fr": "PROCESSUS & DÉMARRAGE",
        "pt": "PROCESSOS & INICIALIZAÇÃO",
        "ko": "프로세스 및 시작 프로그램",
        "ru": "ПРОЦЕССЫ И АВТОЗАГРУЗКА",
        "ar": "العمليات وبدء التشغيل",
        "hi": "प्रक्रियाएँ और स्टार्टअप",
        "th": "กระบวนการและการเริ่มต้น",
        "vi": "TIẾN TRÌNH & KHỞI ĐỘNG",
        "tr": "İŞLEMLER & BAŞLANGIÇ",
        "it": "PROCESSI & AVVIO",
    },
    "cat_security": {
        "en": "SECURITY & PRIVACY",
        "id": "KEAMANAN dan PRIVASI",
        "es": "SEGURIDAD Y PRIVACIDAD",
        "de": "SICHERHEIT & DATENSCHUTZ",
        "zh": "安全与隐私",
        "ja": "セキュリティとプライバシー",
        "su": "KAAMANAN & PRIVASI",
        "jv": "KEAMANAN & PRIVASI",
        "fr": "SÉCURITÉ & CONFIDENTIALITÉ",
        "pt": "SEGURANÇA & PRIVACIDADE",
        "ko": "보안 및 개인정보",
        "ru": "БЕЗОПАСНОСТЬ И КОНФИДЕНЦИАЛЬНОСТЬ",
        "ar": "الأمان والخصوصية",
        "hi": "सुरक्षा और गोपनीयता",
        "th": "ความปลอดภัยและความเป็นส่วนตัว",
        "vi": "BẢO MẬT & RIÊNG TƯ",
        "tr": "GÜVENLİK & GİZLİLİK",
        "it": "SICUREZZA & PRIVACY",
    },
    "cat_shortcuts": {
        "en": "SHORTCUTS & TOOLS",
        "id": "SHORTCUT dan TOOLS",
        "es": "ATAJOS Y HERRAMIENTAS",
        "de": "VERKNÜPFUNGEN & TOOLS",
        "zh": "快捷方式与工具",
        "ja": "ショートカットとツール",
        "su": "SHORTCUT & ALAT",
        "jv": "SHORTCUT & ALAT",
        "fr": "RACCOURCIS & OUTILS",
        "pt": "ATALHOS & FERRAMENTAS",
        "ko": "바로가기 및 도구",
        "ru": "ЯРЛЫКИ И ИНСТРУМЕНТЫ",
        "ar": "الاختصارات والأدوات",
        "hi": "शॉर्टकट और उपकरण",
        "th": "ทางลัดและเครื่องมือ",
        "vi": "PHÍM TẮT & CÔNG CỤ",
        "tr": "KISAYOLLAR & ARAÇLAR",
        "it": "SCORCIATOIE & STRUMENTI",
    },
    "cat_other": {
        "en": "OTHERS",
        "id": "LAINNYA",
        "es": "OTROS",
        "de": "SONSTIGES",
        "zh": "其他",
        "ja": "その他",
        "su": "SÉJÉNNA",
        "jv": "LIYANÉ",
        "fr": "AUTRES",
        "pt": "OUTROS",
        "ko": "기타",
        "ru": "ПРОЧЕЕ",
        "ar": "أخرى",
        "hi": "अन्य",
        "th": "อื่นๆ",
        "vi": "KHÁC",
        "tr": "DİĞER",
        "it": "ALTRO",
    },

    # ── MENU ITEMS ──
    "menu_shutdown": {
        "en": "Auto Shutdown (Timer)",
        "id": "Shutdown Otomatis (Timer)",
        "es": "Apagado Automático (Temporizador)",
        "de": "Automatisches Herunterfahren (Timer)",
        "zh": "自动关机（定时器）",
        "ja": "自動シャットダウン（タイマー）",
        "su": "Shutdown Otomatis (Timer)",
        "jv": "Shutdown Otomatis (Timer)",
        "fr": "Arrêt Automatique (Minuterie)",
        "pt": "Desligamento Automático (Timer)",
        "ko": "자동 종료 (타이머)",
        "ru": "Автовыключение (Таймер)",
        "ar": "إيقاف تلقائي (مؤقت)",
        "hi": "ऑटो शटडाउन (टाइमर)",
        "th": "ปิดเครื่องอัตโนมัติ (ตั้งเวลา)",
        "vi": "Tắt máy tự động (Hẹn giờ)",
        "tr": "Otomatik Kapatma (Zamanlayıcı)",
        "it": "Spegnimento Automatico (Timer)",
    },
    "menu_restart": {
        "en": "Auto Restart (Timer)",
        "id": "Restart Otomatis (Timer)",
        "es": "Reinicio Automático (Temporizador)",
        "de": "Automatischer Neustart (Timer)",
        "zh": "自动重启（定时器）",
        "ja": "自動再起動（タイマー）",
        "su": "Restart Otomatis (Timer)",
        "jv": "Restart Otomatis (Timer)",
        "fr": "Redémarrage Automatique (Minuterie)",
        "pt": "Reinício Automático (Timer)",
        "ko": "자동 재시작 (타이머)",
        "ru": "Автоперезагрузка (Таймер)",
        "ar": "إعادة تشغيل تلقائي (مؤقت)",
        "hi": "ऑटो रीस्टार्ट (टाइमर)",
        "th": "รีสตาร์ทอัตโนมัติ (ตั้งเวลา)",
        "vi": "Khởi động lại tự động (Hẹn giờ)",
        "tr": "Otomatik Yeniden Başlatma (Zamanlayıcı)",
        "it": "Riavvio Automatico (Timer)",
    },
    "menu_cancel_schedule": {
        "en": "Cancel Shutdown / Restart",
        "id": "Batalkan Shutdown / Restart",
        "es": "Cancelar Apagado / Reinicio",
        "de": "Herunterfahren / Neustart abbrechen",
        "zh": "取消关机/重启",
        "ja": "シャットダウン/再起動をキャンセル",
        "su": "Batalkeun Shutdown / Restart",
        "jv": "Batalake Shutdown / Restart",
        "fr": "Annuler Arrêt / Redémarrage",
        "pt": "Cancelar Desligamento / Reinício",
        "ko": "종료/재시작 취소",
        "ru": "Отменить выключение / перезагрузку",
        "ar": "إلغاء الإيقاف / إعادة التشغيل",
        "hi": "शटडाउन / रीस्टार्ट रद्द करें",
        "th": "ยกเลิกการปิด / รีสตาร์ท",
        "vi": "Hủy tắt máy / Khởi động lại",
        "tr": "Kapatma / Yeniden Başlatmayı İptal Et",
        "it": "Annulla Spegnimento / Riavvio",
    },
    "menu_lock": {
        "en": "Lock Computer",
        "id": "Lock Komputer",
        "es": "Bloquear Computadora",
        "de": "Computer sperren",
        "zh": "锁定计算机",
        "ja": "コンピュータをロック",
        "su": "Konci Komputer",
        "jv": "Kunci Komputer",
        "fr": "Verrouiller l'Ordinateur",
        "pt": "Bloquear Computador",
        "ko": "컴퓨터 잠금",
        "ru": "Заблокировать компьютер",
        "ar": "قفل الكمبيوتر",
        "hi": "कंप्यूटर लॉक करें",
        "th": "ล็อคคอมพิวเตอร์",
        "vi": "Khóa máy tính",
        "tr": "Bilgisayarı Kilitle",
        "it": "Blocca Computer",
    },
    "menu_sleep": {
        "en": "Sleep / Hibernate (Timer)",
        "id": "Sleep / Hibernate (Timer)",
        "es": "Suspender / Hibernar (Temporizador)",
        "de": "Ruhezustand / Energiesparmodus (Timer)",
        "zh": "睡眠/休眠（定时器）",
        "ja": "スリープ/休止状態（タイマー）",
        "su": "Sleep / Hibernate (Timer)",
        "jv": "Sleep / Hibernate (Timer)",
        "fr": "Veille / Hibernation (Minuterie)",
        "pt": "Suspender / Hibernar (Timer)",
        "ko": "절전/최대 절전 (타이머)",
        "ru": "Сон / Гибернация (Таймер)",
        "ar": "سكون / إسبات (مؤقت)",
        "hi": "स्लीप / हाइबरनेट (टाइमर)",
        "th": "สลีป / ไฮเบอร์เนต (ตั้งเวลา)",
        "vi": "Ngủ / Ngủ đông (Hẹn giờ)",
        "tr": "Uyku / Hazırda Beklet (Zamanlayıcı)",
        "it": "Sospensione / Ibernazione (Timer)",
    },
    "menu_sysinfo": {
        "en": "Full System Info",
        "id": "Info Sistem Lengkap",
        "es": "Info del Sistema Completa",
        "de": "Vollständige Systeminfo",
        "zh": "完整系统信息",
        "ja": "完全なシステム情報",
        "su": "Info Sistem Lengkep",
        "jv": "Info Sistem Jangkep",
        "fr": "Info Système Complète",
        "pt": "Info do Sistema Completa",
        "ko": "전체 시스템 정보",
        "ru": "Полная информация о системе",
        "ar": "معلومات النظام الكاملة",
        "hi": "पूर्ण सिस्टम जानकारी",
        "th": "ข้อมูลระบบทั้งหมด",
        "vi": "Thông tin hệ thống đầy đủ",
        "tr": "Tam Sistem Bilgisi",
        "it": "Info Sistema Completa",
    },
    "menu_disk": {
        "en": "Check Disk Space",
        "id": "Cek Disk Space",
        "es": "Verificar Espacio en Disco",
        "de": "Festplattenspeicher prüfen",
        "zh": "检查磁盘空间",
        "ja": "ディスク容量を確認",
        "su": "Cék Ruang Disk",
        "jv": "Cek Ruang Disk",
        "fr": "Vérifier l'Espace Disque",
        "pt": "Verificar Espaço em Disco",
        "ko": "디스크 공간 확인",
        "ru": "Проверить место на диске",
        "ar": "فحص مساحة القرص",
        "hi": "डिस्क स्पेस जाँचें",
        "th": "ตรวจสอบพื้นที่ดิสก์",
        "vi": "Kiểm tra dung lượng đĩa",
        "tr": "Disk Alanını Kontrol Et",
        "it": "Controlla Spazio Disco",
    },
    "menu_battery": {
        "en": "Check Battery Status",
        "id": "Cek Status Baterai",
        "es": "Verificar Estado de Batería",
        "de": "Batteriestatus prüfen",
        "zh": "检查电池状态",
        "ja": "バッテリー状態を確認",
        "su": "Cék Status Bateré",
        "jv": "Cek Status Baterai",
        "fr": "Vérifier l'État de la Batterie",
        "pt": "Verificar Status da Bateria",
        "ko": "배터리 상태 확인",
        "ru": "Проверить состояние батареи",
        "ar": "فحص حالة البطارية",
        "hi": "बैटरी स्थिति जाँचें",
        "th": "ตรวจสอบสถานะแบตเตอรี่",
        "vi": "Kiểm tra tình trạng pin",
        "tr": "Pil Durumunu Kontrol Et",
        "it": "Controlla Stato Batteria",
    },
    "menu_uptime": {
        "en": "Check Computer Uptime",
        "id": "Cek Uptime Komputer",
        "es": "Verificar Tiempo de Actividad",
        "de": "Betriebszeit prüfen",
        "zh": "检查运行时间",
        "ja": "稼働時間を確認",
        "su": "Cék Uptime Komputer",
        "jv": "Cek Uptime Komputer",
        "fr": "Vérifier le Temps de Fonctionnement",
        "pt": "Verificar Tempo de Atividade",
        "ko": "컴퓨터 가동 시간 확인",
        "ru": "Проверить время работы",
        "ar": "فحص وقت تشغيل الكمبيوتر",
        "hi": "कंप्यूटर अपटाइम जाँचें",
        "th": "ตรวจสอบเวลาทำงาน",
        "vi": "Kiểm tra thời gian hoạt động",
        "tr": "Bilgisayar Çalışma Süresini Kontrol Et",
        "it": "Controlla Tempo di Attività",
    },
    "menu_monitor": {
        "en": "Real-Time Monitor (CPU/RAM/NET)",
        "id": "Monitor Real-Time (CPU/RAM/NET)",
        "es": "Monitor en Tiempo Real (CPU/RAM/RED)",
        "de": "Echtzeit-Monitor (CPU/RAM/NETZ)",
        "zh": "实时监控（CPU/RAM/网络）",
        "ja": "リアルタイムモニター（CPU/RAM/NET）",
        "su": "Monitor Real-Time (CPU/RAM/NET)",
        "jv": "Monitor Real-Time (CPU/RAM/NET)",
        "fr": "Moniteur Temps Réel (CPU/RAM/NET)",
        "pt": "Monitor em Tempo Real (CPU/RAM/NET)",
        "ko": "실시간 모니터 (CPU/RAM/NET)",
        "ru": "Мониторинг в реальном времени (CPU/RAM/NET)",
        "ar": "مراقبة فورية (CPU/RAM/NET)",
        "hi": "रियल-टाइम मॉनिटर (CPU/RAM/NET)",
        "th": "มอนิเตอร์แบบเรียลไทม์ (CPU/RAM/NET)",
        "vi": "Giám sát thời gian thực (CPU/RAM/NET)",
        "tr": "Gerçek Zamanlı İzleme (CPU/RAM/NET)",
        "it": "Monitor Tempo Reale (CPU/RAM/NET)",
    },
    "menu_gpu": {
        "en": "GPU / VGA Info",
        "id": "Info GPU / VGA",
        "es": "Info GPU / VGA",
        "de": "GPU / VGA Info",
        "zh": "GPU / VGA 信息",
        "ja": "GPU / VGA 情報",
        "su": "Info GPU / VGA",
        "jv": "Info GPU / VGA",
        "fr": "Info GPU / VGA",
        "pt": "Info GPU / VGA",
        "ko": "GPU / VGA 정보",
        "ru": "Информация о GPU / VGA",
        "ar": "معلومات GPU / VGA",
        "hi": "GPU / VGA जानकारी",
        "th": "ข้อมูล GPU / VGA",
        "vi": "Thông tin GPU / VGA",
        "tr": "GPU / VGA Bilgisi",
        "it": "Info GPU / VGA",
    },
    "menu_userinfo": {
        "en": "User Info Detail",
        "id": "Info User Detail",
        "es": "Detalle de Info de Usuario",
        "de": "Benutzerinfo Detail",
        "zh": "用户详细信息",
        "ja": "ユーザー情報詳細",
        "su": "Info User Detil",
        "jv": "Info User Detail",
        "fr": "Détail Info Utilisateur",
        "pt": "Detalhe Info do Usuário",
        "ko": "사용자 정보 상세",
        "ru": "Подробная информация о пользователе",
        "ar": "تفاصيل معلومات المستخدم",
        "hi": "उपयोगकर्ता जानकारी विवरण",
        "th": "รายละเอียดข้อมูลผู้ใช้",
        "vi": "Chi tiết thông tin người dùng",
        "tr": "Kullanıcı Bilgisi Detayı",
        "it": "Dettaglio Info Utente",
    },
    "menu_hardware": {
        "en": "Full Hardware Summary",
        "id": "Ringkasan Hardware Lengkap",
        "es": "Resumen Completo de Hardware",
        "de": "Vollständige Hardware-Zusammenfassung",
        "zh": "完整硬件摘要",
        "ja": "完全なハードウェアサマリー",
        "su": "Ringkesan Hardware Lengkep",
        "jv": "Ringkesan Hardware Jangkep",
        "fr": "Résumé Matériel Complet",
        "pt": "Resumo Completo de Hardware",
        "ko": "전체 하드웨어 요약",
        "ru": "Полная сводка оборудования",
        "ar": "ملخص الأجهزة الكامل",
        "hi": "पूर्ण हार्डवेयर सारांश",
        "th": "สรุปฮาร์ดแวร์ทั้งหมด",
        "vi": "Tóm tắt phần cứng đầy đủ",
        "tr": "Tam Donanım Özeti",
        "it": "Riepilogo Hardware Completo",
    },
    "menu_checkip": {
        "en": "Check IP Address",
        "id": "Cek IP Address",
        "es": "Verificar Dirección IP",
        "de": "IP-Adresse prüfen",
        "zh": "检查IP地址",
        "ja": "IPアドレスを確認",
        "su": "Cék IP Address",
        "jv": "Cek IP Address",
        "fr": "Vérifier l'Adresse IP",
        "pt": "Verificar Endereço IP",
        "ko": "IP 주소 확인",
        "ru": "Проверить IP-адрес",
        "ar": "فحص عنوان IP",
        "hi": "IP पता जाँचें",
        "th": "ตรวจสอบที่อยู่ IP",
        "vi": "Kiểm tra địa chỉ IP",
        "tr": "IP Adresini Kontrol Et",
        "it": "Controlla Indirizzo IP",
    },
    "menu_ipdetail": {
        "en": "IP Real - Full Detail",
        "id": "IP Real - Detail Lengkap",
        "es": "IP Real - Detalle Completo",
        "de": "IP Real - Vollständige Details",
        "zh": "真实IP - 完整详情",
        "ja": "リアルIP - 完全な詳細",
        "su": "IP Real - Detil Lengkep",
        "jv": "IP Real - Detail Jangkep",
        "fr": "IP Réelle - Détail Complet",
        "pt": "IP Real - Detalhe Completo",
        "ko": "실제 IP - 전체 상세",
        "ru": "Реальный IP - Полная информация",
        "ar": "IP الحقيقي - تفاصيل كاملة",
        "hi": "असली IP - पूर्ण विवरण",
        "th": "IP จริง - รายละเอียดทั้งหมด",
        "vi": "IP thực - Chi tiết đầy đủ",
        "tr": "Gerçek IP - Tam Detay",
        "it": "IP Reale - Dettaglio Completo",
    },
    "menu_flushdns": {
        "en": "Flush DNS Cache",
        "id": "Flush DNS Cache",
        "es": "Limpiar Caché DNS",
        "de": "DNS-Cache leeren",
        "zh": "刷新DNS缓存",
        "ja": "DNSキャッシュをフラッシュ",
        "su": "Flush DNS Cache",
        "jv": "Flush DNS Cache",
        "fr": "Vider le Cache DNS",
        "pt": "Limpar Cache DNS",
        "ko": "DNS 캐시 플러시",
        "ru": "Очистить DNS-кеш",
        "ar": "مسح ذاكرة DNS",
        "hi": "DNS कैश फ्लश करें",
        "th": "ล้างแคช DNS",
        "vi": "Xóa bộ nhớ đệm DNS",
        "tr": "DNS Önbelleğini Temizle",
        "it": "Svuota Cache DNS",
    },
    "menu_ping": {
        "en": "Ping Test",
        "id": "Tes Ping",
        "es": "Prueba de Ping",
        "de": "Ping-Test",
        "zh": "Ping测试",
        "ja": "Pingテスト",
        "su": "Tés Ping",
        "jv": "Tes Ping",
        "fr": "Test de Ping",
        "pt": "Teste de Ping",
        "ko": "핑 테스트",
        "ru": "Тест Ping",
        "ar": "اختبار Ping",
        "hi": "पिंग टेस्ट",
        "th": "ทดสอบ Ping",
        "vi": "Kiểm tra Ping",
        "tr": "Ping Testi",
        "it": "Test Ping",
    },
    "menu_traceroute": {
        "en": "Traceroute",
        "id": "Traceroute",
        "es": "Traceroute",
        "de": "Traceroute",
        "zh": "路由追踪",
        "ja": "トレースルート",
        "su": "Traceroute",
        "jv": "Traceroute",
        "fr": "Traceroute",
        "pt": "Traceroute",
        "ko": "경로 추적",
        "ru": "Трассировка маршрута",
        "ar": "تتبع المسار",
        "hi": "ट्रेसरूट",
        "th": "Traceroute",
        "vi": "Traceroute",
        "tr": "Traceroute",
        "it": "Traceroute",
    },
    "menu_dnslookup": {
        "en": "DNS Lookup",
        "id": "DNS Lookup",
        "es": "Búsqueda DNS",
        "de": "DNS-Abfrage",
        "zh": "DNS查询",
        "ja": "DNS検索",
        "su": "DNS Lookup",
        "jv": "DNS Lookup",
        "fr": "Recherche DNS",
        "pt": "Consulta DNS",
        "ko": "DNS 조회",
        "ru": "DNS-запрос",
        "ar": "بحث DNS",
        "hi": "DNS लुकअप",
        "th": "DNS Lookup",
        "vi": "Tra cứu DNS",
        "tr": "DNS Sorgusu",
        "it": "Ricerca DNS",
    },
    "menu_netinfo": {
        "en": "Full Network Info",
        "id": "Info Jaringan Lengkap",
        "es": "Info de Red Completa",
        "de": "Vollständige Netzwerkinfo",
        "zh": "完整网络信息",
        "ja": "完全なネットワーク情報",
        "su": "Info Jaringan Lengkep",
        "jv": "Info Jaringan Jangkep",
        "fr": "Info Réseau Complète",
        "pt": "Info de Rede Completa",
        "ko": "전체 네트워크 정보",
        "ru": "Полная информация о сети",
        "ar": "معلومات الشبكة الكاملة",
        "hi": "पूर्ण नेटवर्क जानकारी",
        "th": "ข้อมูลเครือข่ายทั้งหมด",
        "vi": "Thông tin mạng đầy đủ",
        "tr": "Tam Ağ Bilgisi",
        "it": "Info Rete Completa",
    },
    "menu_wifi_toggle": {
        "en": "Toggle WiFi On/Off",
        "id": "Matikan / Nyalakan WiFi",
        "es": "Activar / Desactivar WiFi",
        "de": "WiFi Ein/Aus",
        "zh": "开关WiFi",
        "ja": "WiFiのオン/オフ",
        "su": "Pareuman / Hurungkeun WiFi",
        "jv": "Mateni / Nguripake WiFi",
        "fr": "Activer / Désactiver WiFi",
        "pt": "Ligar / Desligar WiFi",
        "ko": "WiFi 켜기/끄기",
        "ru": "Включить / Выключить WiFi",
        "ar": "تشغيل / إيقاف WiFi",
        "hi": "WiFi चालू/बंद करें",
        "th": "เปิด/ปิด WiFi",
        "vi": "Bật / Tắt WiFi",
        "tr": "WiFi Aç/Kapat",
        "it": "Attiva / Disattiva WiFi",
    },
    "menu_wifi_pass": {
        "en": "View Saved WiFi Passwords",
        "id": "Lihat Password WiFi Tersimpan",
        "es": "Ver Contraseñas WiFi Guardadas",
        "de": "Gespeicherte WiFi-Passwörter anzeigen",
        "zh": "查看已保存的WiFi密码",
        "ja": "保存されたWiFiパスワードを表示",
        "su": "Tingali Sandi WiFi Nu Disimpen",
        "jv": "Deleng Sandi WiFi Sing Disimpen",
        "fr": "Voir les Mots de Passe WiFi Enregistrés",
        "pt": "Ver Senhas WiFi Salvas",
        "ko": "저장된 WiFi 비밀번호 보기",
        "ru": "Просмотр сохранённых паролей WiFi",
        "ar": "عرض كلمات مرور WiFi المحفوظة",
        "hi": "सहेजे गए WiFi पासवर्ड देखें",
        "th": "ดูรหัสผ่าน WiFi ที่บันทึกไว้",
        "vi": "Xem mật khẩu WiFi đã lưu",
        "tr": "Kayıtlı WiFi Şifrelerini Görüntüle",
        "it": "Visualizza Password WiFi Salvate",
    },
    "menu_speedtest": {
        "en": "Internet Speed Test",
        "id": "Tes Kecepatan Internet",
        "es": "Prueba de Velocidad de Internet",
        "de": "Internet-Geschwindigkeitstest",
        "zh": "网速测试",
        "ja": "インターネット速度テスト",
        "su": "Tés Laju Internet",
        "jv": "Tes Kecepatan Internet",
        "fr": "Test de Vitesse Internet",
        "pt": "Teste de Velocidade da Internet",
        "ko": "인터넷 속도 테스트",
        "ru": "Тест скорости интернета",
        "ar": "اختبار سرعة الإنترنت",
        "hi": "इंटरनेट स्पीड टेस्ट",
        "th": "ทดสอบความเร็วอินเทอร์เน็ต",
        "vi": "Kiểm tra tốc độ Internet",
        "tr": "İnternet Hız Testi",
        "it": "Test Velocità Internet",
    },
    "menu_cleantemp": {
        "en": "Clean Temporary Files",
        "id": "Bersihkan File Temporary",
        "es": "Limpiar Archivos Temporales",
        "de": "Temporäre Dateien bereinigen",
        "zh": "清理临时文件",
        "ja": "一時ファイルをクリーンアップ",
        "su": "Beresihkeun File Samentara",
        "jv": "Resiki File Sementara",
        "fr": "Nettoyer les Fichiers Temporaires",
        "pt": "Limpar Arquivos Temporários",
        "ko": "임시 파일 정리",
        "ru": "Очистить временные файлы",
        "ar": "تنظيف الملفات المؤقتة",
        "hi": "अस्थायी फ़ाइलें साफ़ करें",
        "th": "ล้างไฟล์ชั่วคราว",
        "vi": "Dọn dẹp tệp tạm",
        "tr": "Geçici Dosyaları Temizle",
        "it": "Pulisci File Temporanei",
    },
    "menu_cleanbin": {
        "en": "Clean Recycle Bin",
        "id": "Bersihkan Recycle Bin",
        "es": "Vaciar Papelera de Reciclaje",
        "de": "Papierkorb leeren",
        "zh": "清空回收站",
        "ja": "ごみ箱を空にする",
        "su": "Beresihkeun Recycle Bin",
        "jv": "Resiki Recycle Bin",
        "fr": "Vider la Corbeille",
        "pt": "Limpar Lixeira",
        "ko": "휴지통 비우기",
        "ru": "Очистить корзину",
        "ar": "تفريغ سلة المحذوفات",
        "hi": "रीसायकल बिन साफ़ करें",
        "th": "ล้างถังขยะ",
        "vi": "Dọn thùng rác",
        "tr": "Geri Dönüşüm Kutusunu Temizle",
        "it": "Svuota Cestino",
    },
    "menu_benchmark": {
        "en": "Disk Benchmark",
        "id": "Benchmark Disk",
        "es": "Benchmark de Disco",
        "de": "Festplatten-Benchmark",
        "zh": "磁盘基准测试",
        "ja": "ディスクベンチマーク",
        "su": "Benchmark Disk",
        "jv": "Benchmark Disk",
        "fr": "Benchmark Disque",
        "pt": "Benchmark de Disco",
        "ko": "디스크 벤치마크",
        "ru": "Тест производительности диска",
        "ar": "اختبار أداء القرص",
        "hi": "डिस्क बेंचमार्क",
        "th": "ทดสอบประสิทธิภาพดิสก์",
        "vi": "Benchmark ổ đĩa",
        "tr": "Disk Benchmark",
        "it": "Benchmark Disco",
    },
    "menu_running": {
        "en": "Running Programs (Top 20 RAM)",
        "id": "Program Berjalan (Top 20 RAM)",
        "es": "Programas en Ejecución (Top 20 RAM)",
        "de": "Laufende Programme (Top 20 RAM)",
        "zh": "运行中的程序（RAM前20）",
        "ja": "実行中のプログラム（RAM上位20）",
        "su": "Program Jalan (Top 20 RAM)",
        "jv": "Program Mlaku (Top 20 RAM)",
        "fr": "Programmes en Cours (Top 20 RAM)",
        "pt": "Programas em Execução (Top 20 RAM)",
        "ko": "실행 중인 프로그램 (RAM 상위 20)",
        "ru": "Запущенные программы (Топ 20 RAM)",
        "ar": "البرامج قيد التشغيل (أعلى 20 RAM)",
        "hi": "चल रहे प्रोग्राम (शीर्ष 20 RAM)",
        "th": "โปรแกรมที่ทำงาน (Top 20 RAM)",
        "vi": "Chương trình đang chạy (Top 20 RAM)",
        "tr": "Çalışan Programlar (En Çok 20 RAM)",
        "it": "Programmi in Esecuzione (Top 20 RAM)",
    },
    "menu_killproc": {
        "en": "Find & Kill Process",
        "id": "Cari dan Matikan Proses",
        "es": "Buscar y Terminar Proceso",
        "de": "Prozess suchen & beenden",
        "zh": "查找并终止进程",
        "ja": "プロセスの検索と終了",
        "su": "Milarian & Matékeun Prosés",
        "jv": "Goleki & Mateni Proses",
        "fr": "Trouver & Terminer un Processus",
        "pt": "Encontrar & Encerrar Processo",
        "ko": "프로세스 찾기 및 종료",
        "ru": "Найти и завершить процесс",
        "ar": "البحث وإنهاء العملية",
        "hi": "प्रक्रिया खोजें और बंद करें",
        "th": "ค้นหาและยุติกระบวนการ",
        "vi": "Tìm & Kết thúc tiến trình",
        "tr": "İşlem Bul & Sonlandır",
        "it": "Trova & Termina Processo",
    },
    "menu_startup": {
        "en": "Startup Manager",
        "id": "Startup Manager",
        "es": "Gestor de Inicio",
        "de": "Autostart-Manager",
        "zh": "启动管理器",
        "ja": "スタートアップマネージャー",
        "su": "Manajer Startup",
        "jv": "Manajer Startup",
        "fr": "Gestionnaire de Démarrage",
        "pt": "Gerenciador de Inicialização",
        "ko": "시작 프로그램 관리자",
        "ru": "Менеджер автозагрузки",
        "ar": "مدير بدء التشغيل",
        "hi": "स्टार्टअप मैनेजर",
        "th": "ตัวจัดการเริ่มต้น",
        "vi": "Quản lý khởi động",
        "tr": "Başlangıç Yöneticisi",
        "it": "Gestore Avvio",
    },
    "menu_secoverview": {
        "en": "Computer Security Overview",
        "id": "Ringkasan Keamanan Komputer",
        "es": "Resumen de Seguridad del Computador",
        "de": "Sicherheitsübersicht",
        "zh": "计算机安全概览",
        "ja": "コンピュータセキュリティ概要",
        "su": "Ringkesan Kaamanan Komputer",
        "jv": "Ringkesan Keamanan Komputer",
        "fr": "Aperçu de la Sécurité",
        "pt": "Visão Geral de Segurança",
        "ko": "컴퓨터 보안 개요",
        "ru": "Обзор безопасности компьютера",
        "ar": "نظرة عامة على أمان الكمبيوتر",
        "hi": "कंप्यूटर सुरक्षा अवलोकन",
        "th": "ภาพรวมความปลอดภัยคอมพิวเตอร์",
        "vi": "Tổng quan bảo mật máy tính",
        "tr": "Bilgisayar Güvenlik Özeti",
        "it": "Panoramica Sicurezza Computer",
    },
    "menu_firewall": {
        "en": "Check Firewall Status",
        "id": "Cek Status Firewall",
        "es": "Verificar Estado del Firewall",
        "de": "Firewall-Status prüfen",
        "zh": "检查防火墙状态",
        "ja": "ファイアウォール状態を確認",
        "su": "Cék Status Firewall",
        "jv": "Cek Status Firewall",
        "fr": "Vérifier l'État du Pare-feu",
        "pt": "Verificar Status do Firewall",
        "ko": "방화벽 상태 확인",
        "ru": "Проверить состояние брандмауэра",
        "ar": "فحص حالة جدار الحماية",
        "hi": "फ़ायरवॉल स्थिति जाँचें",
        "th": "ตรวจสอบสถานะไฟร์วอลล์",
        "vi": "Kiểm tra trạng thái tường lửa",
        "tr": "Güvenlik Duvarı Durumunu Kontrol Et",
        "it": "Controlla Stato Firewall",
    },
    "menu_ports": {
        "en": "Check Open Ports",
        "id": "Cek Port Terbuka",
        "es": "Verificar Puertos Abiertos",
        "de": "Offene Ports prüfen",
        "zh": "检查开放端口",
        "ja": "開いているポートを確認",
        "su": "Cék Port Kabuka",
        "jv": "Cek Port Mbukak",
        "fr": "Vérifier les Ports Ouverts",
        "pt": "Verificar Portas Abertas",
        "ko": "열린 포트 확인",
        "ru": "Проверить открытые порты",
        "ar": "فحص المنافذ المفتوحة",
        "hi": "खुले पोर्ट जाँचें",
        "th": "ตรวจสอบพอร์ตที่เปิดอยู่",
        "vi": "Kiểm tra cổng mở",
        "tr": "Açık Portları Kontrol Et",
        "it": "Controlla Porte Aperte",
    },
    "menu_antivirus": {
        "en": "Check Antivirus Status",
        "id": "Cek Status Antivirus",
        "es": "Verificar Estado del Antivirus",
        "de": "Antivirus-Status prüfen",
        "zh": "检查杀毒软件状态",
        "ja": "アンチウイルス状態を確認",
        "su": "Cék Status Antivirus",
        "jv": "Cek Status Antivirus",
        "fr": "Vérifier l'État de l'Antivirus",
        "pt": "Verificar Status do Antivírus",
        "ko": "안티바이러스 상태 확인",
        "ru": "Проверить состояние антивируса",
        "ar": "فحص حالة مضاد الفيروسات",
        "hi": "एंटीवायरस स्थिति जाँचें",
        "th": "ตรวจสอบสถานะแอนตี้ไวรัส",
        "vi": "Kiểm tra trạng thái diệt virus",
        "tr": "Antivirüs Durumunu Kontrol Et",
        "it": "Controlla Stato Antivirus",
    },
    "menu_suspicious": {
        "en": "Scan Suspicious Connections",
        "id": "Scan Koneksi Mencurigakan",
        "es": "Escanear Conexiones Sospechosas",
        "de": "Verdächtige Verbindungen scannen",
        "zh": "扫描可疑连接",
        "ja": "不審な接続をスキャン",
        "su": "Scan Konéksi Curiga",
        "jv": "Scan Koneksi Curiga",
        "fr": "Scanner les Connexions Suspectes",
        "pt": "Escanear Conexões Suspeitas",
        "ko": "의심스러운 연결 스캔",
        "ru": "Сканировать подозрительные соединения",
        "ar": "فحص الاتصالات المشبوهة",
        "hi": "संदिग्ध कनेक्शन स्कैन करें",
        "th": "สแกนการเชื่อมต่อที่น่าสงสัย",
        "vi": "Quét kết nối đáng ngờ",
        "tr": "Şüpheli Bağlantıları Tara",
        "it": "Scansiona Connessioni Sospette",
    },
    "menu_useraccount": {
        "en": "Check User Accounts",
        "id": "Cek Akun User",
        "es": "Verificar Cuentas de Usuario",
        "de": "Benutzerkonten prüfen",
        "zh": "检查用户账户",
        "ja": "ユーザーアカウントを確認",
        "su": "Cék Akun User",
        "jv": "Cek Akun User",
        "fr": "Vérifier les Comptes Utilisateur",
        "pt": "Verificar Contas de Usuário",
        "ko": "사용자 계정 확인",
        "ru": "Проверить учётные записи",
        "ar": "فحص حسابات المستخدمين",
        "hi": "उपयोगकर्ता खाते जाँचें",
        "th": "ตรวจสอบบัญชีผู้ใช้",
        "vi": "Kiểm tra tài khoản người dùng",
        "tr": "Kullanıcı Hesaplarını Kontrol Et",
        "it": "Controlla Account Utente",
    },
    "menu_privacy": {
        "en": "Privacy Cleaner",
        "id": "Privacy Cleaner",
        "es": "Limpiador de Privacidad",
        "de": "Datenschutz-Reiniger",
        "zh": "隐私清理器",
        "ja": "プライバシークリーナー",
        "su": "Pembersih Privasi",
        "jv": "Pembersih Privasi",
        "fr": "Nettoyeur de Confidentialité",
        "pt": "Limpador de Privacidade",
        "ko": "개인정보 클리너",
        "ru": "Очистка конфиденциальности",
        "ar": "منظف الخصوصية",
        "hi": "गोपनीयता क्लीनर",
        "th": "ตัวล้างความเป็นส่วนตัว",
        "vi": "Dọn dẹp riêng tư",
        "tr": "Gizlilik Temizleyici",
        "it": "Pulizia Privacy",
    },
    "menu_applauncher": {
        "en": "App Launcher",
        "id": "Buka Aplikasi (App Launcher)",
        "es": "Lanzador de Aplicaciones",
        "de": "App-Starter",
        "zh": "应用启动器",
        "ja": "アプリランチャー",
        "su": "Buka Aplikasi",
        "jv": "Buka Aplikasi",
        "fr": "Lanceur d'Applications",
        "pt": "Lançador de Aplicativos",
        "ko": "앱 런처",
        "ru": "Запуск приложений",
        "ar": "مشغل التطبيقات",
        "hi": "ऐप लॉन्चर",
        "th": "ตัวเปิดแอป",
        "vi": "Trình khởi chạy ứng dụng",
        "tr": "Uygulama Başlatıcı",
        "it": "Avvio Applicazioni",
    },
    "menu_screenshot": {
        "en": "Take Screenshot",
        "id": "Ambil Screenshot",
        "es": "Tomar Captura de Pantalla",
        "de": "Screenshot erstellen",
        "zh": "截屏",
        "ja": "スクリーンショットを撮る",
        "su": "Candak Screenshot",
        "jv": "Njupuk Screenshot",
        "fr": "Prendre une Capture d'Écran",
        "pt": "Tirar Captura de Tela",
        "ko": "스크린샷 찍기",
        "ru": "Сделать снимок экрана",
        "ar": "التقاط لقطة شاشة",
        "hi": "स्क्रीनशॉट लें",
        "th": "ถ่ายภาพหน้าจอ",
        "vi": "Chụp ảnh màn hình",
        "tr": "Ekran Görüntüsü Al",
        "it": "Cattura Schermata",
    },
    "menu_quicksettings": {
        "en": "Windows Settings Shortcuts",
        "id": "Shortcut Pengaturan Windows",
        "es": "Atajos de Configuración de Windows",
        "de": "Windows-Einstellungen Verknüpfungen",
        "zh": "Windows设置快捷方式",
        "ja": "Windows設定ショートカット",
        "su": "Shortcut Setélan Windows",
        "jv": "Shortcut Pengaturan Windows",
        "fr": "Raccourcis Paramètres Windows",
        "pt": "Atalhos de Configurações do Windows",
        "ko": "Windows 설정 바로가기",
        "ru": "Ярлыки настроек Windows",
        "ar": "اختصارات إعدادات Windows",
        "hi": "Windows सेटिंग्स शॉर्टकट",
        "th": "ทางลัดการตั้งค่า Windows",
        "vi": "Phím tắt cài đặt Windows",
        "tr": "Windows Ayarları Kısayolları",
        "it": "Scorciatoie Impostazioni Windows",
    },
    "menu_sysshortcuts": {
        "en": "Quick System Actions",
        "id": "Aksi Sistem Cepat",
        "es": "Acciones Rápidas del Sistema",
        "de": "Schnelle Systemaktionen",
        "zh": "快速系统操作",
        "ja": "クイックシステムアクション",
        "su": "Aksi Sistem Gancang",
        "jv": "Aksi Sistem Cepet",
        "fr": "Actions Système Rapides",
        "pt": "Ações Rápidas do Sistema",
        "ko": "빠른 시스템 작업",
        "ru": "Быстрые действия системы",
        "ar": "إجراءات النظام السريعة",
        "hi": "त्वरित सिस्टम क्रियाएँ",
        "th": "การดำเนินการระบบอย่างรวดเร็ว",
        "vi": "Thao tác hệ thống nhanh",
        "tr": "Hızlı Sistem İşlemleri",
        "it": "Azioni Rapide di Sistema",
    },
    "menu_settings": {
        "en": "Settings (Theme & Animation)",
        "id": "Settings (Ubah Tema & Animasi)",
        "es": "Configuración (Tema y Animación)",
        "de": "Einstellungen (Design & Animation)",
        "zh": "设置（主题和动画）",
        "ja": "設定（テーマとアニメーション）",
        "su": "Setélan (Téma & Animasi)",
        "jv": "Pengaturan (Tema & Animasi)",
        "fr": "Paramètres (Thème & Animation)",
        "pt": "Configurações (Tema & Animação)",
        "ko": "설정 (테마 및 애니메이션)",
        "ru": "Настройки (Тема и анимация)",
        "ar": "الإعدادات (السمة والرسوم المتحركة)",
        "hi": "सेटिंग्स (थीम और एनिमेशन)",
        "th": "การตั้งค่า (ธีมและแอนิเมชัน)",
        "vi": "Cài đặt (Giao diện & Hoạt ảnh)",
        "tr": "Ayarlar (Tema & Animasyon)",
        "it": "Impostazioni (Tema & Animazione)",
    },
    "menu_language": {
        "en": "Change Language",
        "id": "Ganti Bahasa",
        "es": "Cambiar Idioma",
        "de": "Sprache ändern",
        "zh": "更改语言",
        "ja": "言語を変更",
        "su": "Ganti Basa",
        "jv": "Ganti Basa",
        "fr": "Changer la Langue",
        "pt": "Mudar Idioma",
        "ko": "언어 변경",
        "ru": "Изменить язык",
        "ar": "تغيير اللغة",
        "hi": "भाषा बदलें",
        "th": "เปลี่ยนภาษา",
        "vi": "Đổi ngôn ngữ",
        "tr": "Dili Değiştir",
        "it": "Cambia Lingua",
    },
    "menu_exit": {
        "en": "Exit",
        "id": "Keluar",
        "es": "Salir",
        "de": "Beenden",
        "zh": "退出",
        "ja": "終了",
        "su": "Kaluar",
        "jv": "Metu",
        "fr": "Quitter",
        "pt": "Sair",
        "ko": "종료",
        "ru": "Выход",
        "ar": "خروج",
        "hi": "बाहर निकलें",
        "th": "ออก",
        "vi": "Thoát",
        "tr": "Çıkış",
        "it": "Esci",
    },

    # ── COMMON UI STRINGS ──
    "select_menu": {
        "en": "Select menu",
        "id": "Pilih menu",
        "es": "Seleccionar menú",
        "de": "Menü auswählen",
        "zh": "选择菜单",
        "ja": "メニューを選択",
        "su": "Pilih menu",
        "jv": "Pilih menu",
        "fr": "Sélectionner le menu",
        "pt": "Selecionar menu",
        "ko": "메뉴 선택",
        "ru": "Выберите меню",
        "ar": "اختر القائمة",
        "hi": "मेनू चुनें",
        "th": "เลือกเมนู",
        "vi": "Chọn menu",
        "tr": "Menü seçin",
        "it": "Seleziona menu",
    },
    "press_enter": {
        "en": "Press Enter to return to menu...",
        "id": "Tekan Enter untuk kembali ke menu...",
        "es": "Presione Enter para volver al menú...",
        "de": "Drücken Sie Enter, um zum Menü zurückzukehren...",
        "zh": "按回车键返回菜单...",
        "ja": "Enterキーを押してメニューに戻る...",
        "su": "Pencét Enter pikeun balik ka menu...",
        "jv": "Pencet Enter kanggo bali menyang menu...",
        "fr": "Appuyez sur Entrée pour revenir au menu...",
        "pt": "Pressione Enter para voltar ao menu...",
        "ko": "메뉴로 돌아가려면 Enter를 누르세요...",
        "ru": "Нажмите Enter для возврата в меню...",
        "ar": "اضغط Enter للعودة إلى القائمة...",
        "hi": "मेनू पर लौटने के लिए Enter दबाएँ...",
        "th": "กด Enter เพื่อกลับไปที่เมนู...",
        "vi": "Nhấn Enter để quay lại menu...",
        "tr": "Menüye dönmek için Enter'a basın...",
        "it": "Premi Invio per tornare al menu...",
    },
    "invalid_choice": {
        "en": "Invalid choice!",
        "id": "Pilihan tidak valid!",
        "es": "¡Opción no válida!",
        "de": "Ungültige Auswahl!",
        "zh": "无效选择！",
        "ja": "無効な選択です！",
        "su": "Pilihan teu valid!",
        "jv": "Pilihan ora valid!",
        "fr": "Choix invalide !",
        "pt": "Escolha inválida!",
        "ko": "잘못된 선택!",
        "ru": "Неверный выбор!",
        "ar": "خيار غير صالح!",
        "hi": "अमान्य विकल्प!",
        "th": "ตัวเลือกไม่ถูกต้อง!",
        "vi": "Lựa chọn không hợp lệ!",
        "tr": "Geçersiz seçim!",
        "it": "Scelta non valida!",
    },
    "goodbye_thanks": {
        "en": "Thank you for using",
        "id": "Terima kasih sudah menggunakan",
        "es": "Gracias por usar",
        "de": "Vielen Dank für die Nutzung von",
        "zh": "感谢使用",
        "ja": "ご利用ありがとうございます",
        "su": "Hatur nuhun parantos nganggo",
        "jv": "Matur nuwun sampun ngginakaken",
        "fr": "Merci d'avoir utilisé",
        "pt": "Obrigado por usar",
        "ko": "사용해 주셔서 감사합니다",
        "ru": "Спасибо за использование",
        "ar": "شكرًا لاستخدامك",
        "hi": "उपयोग करने के लिए धन्यवाद",
        "th": "ขอบคุณที่ใช้",
        "vi": "Cảm ơn bạn đã sử dụng",
        "tr": "Kullandığınız için teşekkürler",
        "it": "Grazie per aver usato",
    },
    "goodbye_star": {
        "en": "Don't forget to give a star on GitHub!",
        "id": "Jangan lupa kasih star di GitHub!",
        "es": "¡No olvides dar una estrella en GitHub!",
        "de": "Vergessen Sie nicht, einen Stern auf GitHub zu geben!",
        "zh": "别忘了在GitHub上给个星！",
        "ja": "GitHubでスターをお忘れなく！",
        "su": "Ulah hilap masihan béntang di GitHub!",
        "jv": "Aja lali menehi bintang ing GitHub!",
        "fr": "N'oubliez pas de mettre une étoile sur GitHub !",
        "pt": "Não esqueça de dar uma estrela no GitHub!",
        "ko": "GitHub에서 별을 주는 것을 잊지 마세요!",
        "ru": "Не забудьте поставить звезду на GitHub!",
        "ar": "لا تنسَ إعطاء نجمة على GitHub!",
        "hi": "GitHub पर स्टार देना न भूलें!",
        "th": "อย่าลืมให้ดาวบน GitHub!",
        "vi": "Đừng quên cho sao trên GitHub!",
        "tr": "GitHub'da yıldız vermeyi unutmayın!",
        "it": "Non dimenticare di mettere una stella su GitHub!",
    },
    "goodbye_see_you": {
        "en": "See you again!",
        "id": "Sampai jumpa lagi!",
        "es": "¡Hasta la vista!",
        "de": "Auf Wiedersehen!",
        "zh": "再见！",
        "ja": "またお会いしましょう！",
        "su": "Dugi tepang deui!",
        "jv": "Sampun jumpa malih!",
        "fr": "À bientôt !",
        "pt": "Até logo!",
        "ko": "또 만나요!",
        "ru": "До встречи!",
        "ar": "إلى اللقاء!",
        "hi": "फिर मिलेंगे!",
        "th": "แล้วพบกันใหม่!",
        "vi": "Hẹn gặp lại!",
        "tr": "Tekrar görüşmek üzere!",
        "it": "Arrivederci!",
    },
    "closing_app": {
        "en": "Closing MultiTool",
        "id": "Menutup MultiTool",
        "es": "Cerrando MultiTool",
        "de": "MultiTool wird geschlossen",
        "zh": "正在关闭 MultiTool",
        "ja": "MultiTool を終了しています",
        "su": "Nutup MultiTool",
        "jv": "Nutup MultiTool",
        "fr": "Fermeture de MultiTool",
        "pt": "Fechando MultiTool",
        "ko": "MultiTool 종료 중",
        "ru": "Закрытие MultiTool",
        "ar": "إغلاق MultiTool",
        "hi": "MultiTool बंद हो रहा है",
        "th": "กำลังปิด MultiTool",
        "vi": "Đang đóng MultiTool",
        "tr": "MultiTool kapatılıyor",
        "it": "Chiusura di MultiTool",
    },
    "stopped_by_user": {
        "en": "Program stopped by user. See you again!",
        "id": "Program dihentikan oleh user. Sampai jumpa!",
        "es": "Programa detenido por el usuario. ¡Hasta luego!",
        "de": "Programm vom Benutzer gestoppt. Auf Wiedersehen!",
        "zh": "程序被用户停止。再见！",
        "ja": "ユーザーによりプログラムが停止されました。さようなら！",
        "su": "Program dieureunkeun ku user. Dugi tepang deui!",
        "jv": "Program diendhegake dening user. Sampun jumpa malih!",
        "fr": "Programme arrêté par l'utilisateur. À bientôt !",
        "pt": "Programa parado pelo usuário. Até logo!",
        "ko": "사용자에 의해 프로그램이 중지되었습니다. 또 만나요!",
        "ru": "Программа остановлена пользователем. До встречи!",
        "ar": "تم إيقاف البرنامج من قبل المستخدم. إلى اللقاء!",
        "hi": "प्रोग्राम उपयोगकर्ता द्वारा रोका गया। फिर मिलेंगे!",
        "th": "โปรแกรมถูกหยุดโดยผู้ใช้ แล้วพบกันใหม่!",
        "vi": "Chương trình bị dừng bởi người dùng. Hẹn gặp lại!",
        "tr": "Program kullanıcı tarafından durduruldu. Tekrar görüşmek üzere!",
        "it": "Programma fermato dall'utente. Arrivederci!",
    },
    "select_language": {
        "en": "Select your language",
        "id": "Pilih bahasa kamu",
        "es": "Selecciona tu idioma",
        "de": "Wählen Sie Ihre Sprache",
        "zh": "选择你的语言",
        "ja": "言語を選択してください",
        "su": "Pilih basa anjeun",
        "jv": "Pilih basa sampeyan",
        "fr": "Sélectionnez votre langue",
        "pt": "Selecione seu idioma",
        "ko": "언어를 선택하세요",
        "ru": "Выберите ваш язык",
        "ar": "اختر لغتك",
        "hi": "अपनी भाषा चुनें",
        "th": "เลือกภาษาของคุณ",
        "vi": "Chọn ngôn ngữ của bạn",
        "tr": "Dilinizi seçin",
        "it": "Seleziona la tua lingua",
    },
    "current_language": {
        "en": "Current language",
        "id": "Bahasa saat ini",
        "es": "Idioma actual",
        "de": "Aktuelle Sprache",
        "zh": "当前语言",
        "ja": "現在の言語",
        "su": "Basa ayeuna",
        "jv": "Basa saiki",
        "fr": "Langue actuelle",
        "pt": "Idioma atual",
        "ko": "현재 언어",
        "ru": "Текущий язык",
        "ar": "اللغة الحالية",
        "hi": "वर्तमान भाषा",
        "th": "ภาษาปัจจุบัน",
        "vi": "Ngôn ngữ hiện tại",
        "tr": "Mevcut dil",
        "it": "Lingua attuale",
    },
    "language_changed": {
        "en": "Language changed to",
        "id": "Bahasa diubah ke",
        "es": "Idioma cambiado a",
        "de": "Sprache geändert zu",
        "zh": "语言已更改为",
        "ja": "言語が変更されました",
        "su": "Basa dirobih ka",
        "jv": "Basa diganti dadi",
        "fr": "Langue changée en",
        "pt": "Idioma alterado para",
        "ko": "언어가 변경되었습니다",
        "ru": "Язык изменён на",
        "ar": "تم تغيير اللغة إلى",
        "hi": "भाषा बदल दी गई",
        "th": "เปลี่ยนภาษาเป็น",
        "vi": "Đã đổi ngôn ngữ sang",
        "tr": "Dil şu dile değiştirildi",
        "it": "Lingua cambiata in",
    },
    "loading_components": {
        "en": "Loading components",
        "id": "Memuat komponen",
        "es": "Cargando componentes",
        "de": "Komponenten werden geladen",
        "zh": "加载组件中",
        "ja": "コンポーネントを読み込み中",
        "su": "Ngamuat komponén",
        "jv": "Ngemot komponen",
        "fr": "Chargement des composants",
        "pt": "Carregando componentes",
        "ko": "구성 요소 로딩 중",
        "ru": "Загрузка компонентов",
        "ar": "جاري تحميل المكونات",
        "hi": "घटक लोड हो रहे हैं",
        "th": "กำลังโหลดส่วนประกอบ",
        "vi": "Đang tải thành phần",
        "tr": "Bileşenler yükleniyor",
        "it": "Caricamento componenti",
    },

    # ── TIPS ──
    "tip_admin": {
        "en": "💡 Tip: Run as Admin for full access to all features!",
        "id": "💡 Tip: Jalankan sebagai Admin untuk akses penuh semua fitur!",
        "es": "💡 Tip: ¡Ejecute como Admin para acceso completo!",
        "de": "💡 Tipp: Als Admin ausführen für vollen Zugriff!",
        "zh": "💡 提示：以管理员身份运行以获取所有功能的完全访问权限！",
        "ja": "💡 ヒント：すべての機能にアクセスするには管理者として実行してください！",
        "su": "💡 Tip: Jalankeun salaku Admin pikeun aksés pinuh!",
        "jv": "💡 Tip: Jalanake minangka Admin kanggo akses kebak!",
        "fr": "💡 Astuce : Exécutez en tant qu'Admin pour un accès complet !",
        "pt": "💡 Dica: Execute como Admin para acesso total!",
        "ko": "💡 팁: 모든 기능에 액세스하려면 관리자로 실행하세요!",
        "ru": "💡 Совет: Запустите от имени администратора для полного доступа!",
        "ar": "💡 نصيحة: شغّل كمسؤول للوصول الكامل!",
        "hi": "💡 टिप: सभी सुविधाओं के लिए एडमिन के रूप में चलाएँ!",
        "th": "💡 เคล็ดลับ: เรียกใช้ในฐานะ Admin เพื่อเข้าถึงทุกฟีเจอร์!",
        "vi": "💡 Mẹo: Chạy với quyền Admin để truy cập đầy đủ!",
        "tr": "💡 İpucu: Tam erişim için Yönetici olarak çalıştırın!",
        "it": "💡 Suggerimento: Esegui come Admin per l'accesso completo!",
    },
    "tip_theme": {
        "en": "💡 Tip: Use Settings to change the color theme.",
        "id": "💡 Tip: Gunakan menu Settings untuk mengubah tema warna.",
        "es": "💡 Tip: Use Configuración para cambiar el tema de color.",
        "de": "💡 Tipp: Verwenden Sie Einstellungen, um das Farbthema zu ändern.",
        "zh": "💡 提示：使用设置更改颜色主题。",
        "ja": "💡 ヒント：設定でカラーテーマを変更できます。",
        "su": "💡 Tip: Paké Setélan pikeun ngarobih téma warna.",
        "jv": "💡 Tip: Nganggo Pengaturan kanggo ngganti tema warna.",
        "fr": "💡 Astuce : Utilisez les Paramètres pour changer le thème.",
        "pt": "💡 Dica: Use Configurações para mudar o tema de cores.",
        "ko": "💡 팁: 설정에서 색상 테마를 변경하세요.",
        "ru": "💡 Совет: Используйте Настройки для смены цветовой темы.",
        "ar": "💡 نصيحة: استخدم الإعدادات لتغيير سمة الألوان.",
        "hi": "💡 टिप: रंग थीम बदलने के लिए सेटिंग्स का उपयोग करें।",
        "th": "💡 เคล็ดลับ: ใช้การตั้งค่าเพื่อเปลี่ยนธีมสี",
        "vi": "💡 Mẹo: Sử dụng Cài đặt để thay đổi giao diện màu.",
        "tr": "💡 İpucu: Renk temasını değiştirmek için Ayarları kullanın.",
        "it": "💡 Suggerimento: Usa le Impostazioni per cambiare il tema colore.",
    },
    "tip_ctrlc": {
        "en": "💡 Tip: Press Ctrl+C to stop a running process.",
        "id": "💡 Tip: Ctrl+C untuk menghentikan proses yang sedang berjalan.",
        "es": "💡 Tip: Presione Ctrl+C para detener un proceso.",
        "de": "💡 Tipp: Drücken Sie Strg+C, um einen laufenden Prozess zu stoppen.",
        "zh": "💡 提示：按Ctrl+C停止正在运行的进程。",
        "ja": "💡 ヒント：Ctrl+Cで実行中のプロセスを停止できます。",
        "su": "💡 Tip: Pencét Ctrl+C pikeun ngeureunkeun prosés.",
        "jv": "💡 Tip: Pencet Ctrl+C kanggo mandegake proses.",
        "fr": "💡 Astuce : Appuyez sur Ctrl+C pour arrêter un processus.",
        "pt": "💡 Dica: Pressione Ctrl+C para parar um processo.",
        "ko": "💡 팁: 실행 중인 프로세스를 중지하려면 Ctrl+C를 누르세요.",
        "ru": "💡 Совет: Нажмите Ctrl+C для остановки процесса.",
        "ar": "💡 نصيحة: اضغط Ctrl+C لإيقاف عملية قيد التشغيل.",
        "hi": "💡 टिप: चल रही प्रक्रिया को रोकने के लिए Ctrl+C दबाएँ।",
        "th": "💡 เคล็ดลับ: กด Ctrl+C เพื่อหยุดกระบวนการ",
        "vi": "💡 Mẹo: Nhấn Ctrl+C để dừng tiến trình đang chạy.",
        "tr": "💡 İpucu: Çalışan bir işlemi durdurmak için Ctrl+C'ye basın.",
        "it": "💡 Suggerimento: Premi Ctrl+C per fermare un processo in esecuzione.",
    },
    "tip_startup": {
        "en": "💡 Tip: Reduce startup programs to speed up boot time.",
        "id": "💡 Tip: Kurangi startup program untuk mempercepat boot PC.",
        "es": "💡 Tip: Reduzca los programas de inicio para acelerar el arranque.",
        "de": "💡 Tipp: Reduzieren Sie Autostart-Programme für schnelleres Booten.",
        "zh": "💡 提示：减少启动程序以加快启动速度。",
        "ja": "💡 ヒント：起動プログラムを減らして起動時間を短縮しましょう。",
        "su": "💡 Tip: Kurangi program startup pikeun ngagancangkeun boot.",
        "jv": "💡 Tip: Kurangi program startup kanggo nyepetake boot.",
        "fr": "💡 Astuce : Réduisez les programmes au démarrage pour accélérer le boot.",
        "pt": "💡 Dica: Reduza programas de inicialização para acelerar o boot.",
        "ko": "💡 팁: 시작 프로그램을 줄여 부팅 속도를 높이세요.",
        "ru": "💡 Совет: Уменьшите количество программ автозагрузки для ускорения загрузки.",
        "ar": "💡 نصيحة: قلل برامج بدء التشغيل لتسريع الإقلاع.",
        "hi": "💡 टिप: बूट समय तेज करने के लिए स्टार्टअप प्रोग्राम कम करें।",
        "th": "💡 เคล็ดลับ: ลดโปรแกรมเริ่มต้นเพื่อเร่งการบูต",
        "vi": "💡 Mẹo: Giảm chương trình khởi động để tăng tốc boot.",
        "tr": "💡 İpucu: Önyükleme süresini hızlandırmak için başlangıç programlarını azaltın.",
        "it": "💡 Suggerimento: Riduci i programmi di avvio per velocizzare il boot.",
    },
    "tip_cleantemp": {
        "en": "💡 Tip: Clean temp files regularly for optimal performance.",
        "id": "💡 Tip: Bersihkan file temp secara rutin untuk performa optimal.",
        "es": "💡 Tip: Limpie archivos temporales regularmente para un rendimiento óptimo.",
        "de": "💡 Tipp: Bereinigen Sie temporäre Dateien regelmäßig für optimale Leistung.",
        "zh": "💡 提示：定期清理临时文件以获得最佳性能。",
        "ja": "💡 ヒント：最適なパフォーマンスのために一時ファイルを定期的にクリーンアップしてください。",
        "su": "💡 Tip: Beresihkeun file temp sacara rutin pikeun performa optimal.",
        "jv": "💡 Tip: Resiki file temp kanthi rutin kanggo performa optimal.",
        "fr": "💡 Astuce : Nettoyez les fichiers temporaires régulièrement.",
        "pt": "💡 Dica: Limpe arquivos temporários regularmente para melhor desempenho.",
        "ko": "💡 팁: 최적의 성능을 위해 임시 파일을 정기적으로 정리하세요.",
        "ru": "💡 Совет: Регулярно очищайте временные файлы для оптимальной производительности.",
        "ar": "💡 نصيحة: نظّف الملفات المؤقتة بانتظام لأداء مثالي.",
        "hi": "💡 टिप: इष्टतम प्रदर्शन के लिए नियमित रूप से अस्थायी फ़ाइलें साफ़ करें।",
        "th": "💡 เคล็ดลับ: ล้างไฟล์ชั่วคราวเป็นประจำเพื่อประสิทธิภาพที่ดี",
        "vi": "💡 Mẹo: Dọn dẹp tệp tạm thường xuyên để có hiệu suất tốt nhất.",
        "tr": "💡 İpucu: Optimum performans için geçici dosyaları düzenli olarak temizleyin.",
        "it": "💡 Suggerimento: Pulisci i file temporanei regolarmente per prestazioni ottimali.",
    },
    "tip_security": {
        "en": "💡 Tip: Check your computer security regularly with Security Overview.",
        "id": "💡 Tip: Cek keamanan komputer secara berkala dengan menu Ringkasan Keamanan.",
        "es": "💡 Tip: Verifique la seguridad de su computadora regularmente.",
        "de": "💡 Tipp: Überprüfen Sie regelmäßig die Sicherheit Ihres Computers.",
        "zh": "💡 提示：定期使用安全概览检查计算机安全。",
        "ja": "💡 ヒント：セキュリティ概要で定期的にコンピュータのセキュリティを確認してください。",
        "su": "💡 Tip: Cék kaamanan komputer sacara rutin.",
        "jv": "💡 Tip: Cek keamanan komputer kanthi rutin.",
        "fr": "💡 Astuce : Vérifiez régulièrement la sécurité de votre ordinateur.",
        "pt": "💡 Dica: Verifique a segurança do computador regularmente.",
        "ko": "💡 팁: 보안 개요로 컴퓨터 보안을 정기적으로 확인하세요.",
        "ru": "💡 Совет: Регулярно проверяйте безопасность компьютера.",
        "ar": "💡 نصيحة: تحقق من أمان حاسوبك بانتظام.",
        "hi": "💡 टिप: सुरक्षा अवलोकन से नियमित रूप से कंप्यूटर सुरक्षा जाँचें।",
        "th": "💡 เคล็ดลับ: ตรวจสอบความปลอดภัยคอมพิวเตอร์เป็นประจำ",
        "vi": "💡 Mẹo: Kiểm tra bảo mật máy tính thường xuyên.",
        "tr": "💡 İpucu: Bilgisayar güvenliğinizi düzenli olarak kontrol edin.",
        "it": "💡 Suggerimento: Controlla regolarmente la sicurezza del computer.",
    },
    "tip_speedtest": {
        "en": "💡 Tip: Use Speed Test to check your internet speed.",
        "id": "💡 Tip: Gunakan Speed Test untuk cek kecepatan internet.",
        "es": "💡 Tip: Use la prueba de velocidad para verificar su internet.",
        "de": "💡 Tipp: Verwenden Sie den Geschwindigkeitstest, um Ihre Internetgeschwindigkeit zu prüfen.",
        "zh": "💡 提示：使用速度测试检查您的网速。",
        "ja": "💡 ヒント：スピードテストでインターネット速度を確認しましょう。",
        "su": "💡 Tip: Paké Speed Test pikeun ngecék laju internet.",
        "jv": "💡 Tip: Nganggo Speed Test kanggo ngecek kecepatan internet.",
        "fr": "💡 Astuce : Utilisez le test de vitesse pour vérifier votre connexion.",
        "pt": "💡 Dica: Use o teste de velocidade para verificar sua internet.",
        "ko": "💡 팁: 속도 테스트로 인터넷 속도를 확인하세요.",
        "ru": "💡 Совет: Используйте тест скорости для проверки интернета.",
        "ar": "💡 نصيحة: استخدم اختبار السرعة لفحص سرعة الإنترنت.",
        "hi": "💡 टिप: इंटरनेट स्पीड जाँचने के लिए स्पीड टेस्ट का उपयोग करें।",
        "th": "💡 เคล็ดลับ: ใช้ Speed Test เพื่อตรวจสอบความเร็วอินเทอร์เน็ต",
        "vi": "💡 Mẹo: Sử dụng Speed Test để kiểm tra tốc độ internet.",
        "tr": "💡 İpucu: İnternet hızınızı kontrol etmek için Hız Testini kullanın.",
        "it": "💡 Suggerimento: Usa il test di velocità per controllare la tua connessione.",
    },
    "tip_privacy": {
        "en": "💡 Tip: Privacy Cleaner helps protect your privacy.",
        "id": "💡 Tip: Privacy Cleaner membantu menjaga privasi kamu.",
        "es": "💡 Tip: El limpiador de privacidad ayuda a proteger su privacidad.",
        "de": "💡 Tipp: Der Datenschutz-Reiniger hilft, Ihre Privatsphäre zu schützen.",
        "zh": "💡 提示：隐私清理器帮助保护您的隐私。",
        "ja": "💡 ヒント：プライバシークリーナーがプライバシーを保護します。",
        "su": "💡 Tip: Privacy Cleaner mantuan ngajaga privasi anjeun.",
        "jv": "💡 Tip: Privacy Cleaner mbantu njaga privasi sampeyan.",
        "fr": "💡 Astuce : Le nettoyeur de confidentialité protège votre vie privée.",
        "pt": "💡 Dica: O limpador de privacidade ajuda a proteger sua privacidade.",
        "ko": "💡 팁: 개인정보 클리너가 개인정보를 보호합니다.",
        "ru": "💡 Совет: Очистка конфиденциальности помогает защитить вашу приватность.",
        "ar": "💡 نصيحة: منظف الخصوصية يساعد في حماية خصوصيتك.",
        "hi": "💡 टिप: गोपनीयता क्लीनर आपकी गोपनीयता की रक्षा करता है।",
        "th": "💡 เคล็ดลับ: Privacy Cleaner ช่วยปกป้องความเป็นส่วนตัวของคุณ",
        "vi": "💡 Mẹo: Privacy Cleaner giúp bảo vệ quyền riêng tư của bạn.",
        "tr": "💡 İpucu: Gizlilik Temizleyici gizliliğinizi korumaya yardımcı olur.",
        "it": "💡 Suggerimento: Il Pulizia Privacy aiuta a proteggere la tua privacy.",
    },
}


# ============================================================
# PUBLIC API FUNCTIONS
# ============================================================
def lang(key, **kwargs):
    """Get translated string for the current language.
    
    Args:
        key: Translation key from TRANSLATIONS dict
        **kwargs: Optional format arguments for string interpolation
    
    Returns:
        Translated string, or English fallback, or the key itself if not found.
    """
    global CURRENT_LANGUAGE
    entry = TRANSLATIONS.get(key)
    if entry is None:
        return key
    text = entry.get(CURRENT_LANGUAGE, entry.get("en", key))
    if kwargs:
        try:
            text = text.format(**kwargs)
        except (KeyError, IndexError):
            pass
    return text


def set_language(code):
    """Set the current language.
    
    Args:
        code: Language code (e.g., 'en', 'id', 'es', etc.)
    
    Returns:
        True if language was set successfully, False otherwise.
    """
    global CURRENT_LANGUAGE
    if code in LANGUAGES:
        CURRENT_LANGUAGE = code
        return True
    return False


def get_current_language():
    """Get the current language code."""
    return CURRENT_LANGUAGE


def get_current_language_name():
    """Get the display name of the current language."""
    info = LANGUAGES.get(CURRENT_LANGUAGE, {})
    return f"{info.get('flag', '')} {info.get('native', CURRENT_LANGUAGE)}"


def get_available_languages():
    """Get list of available languages with metadata.
    
    Returns:
        dict: Language code -> {name, flag, native}
    """
    return LANGUAGES.copy()


def get_tips():
    """Get list of translated tips for the current language."""
    tip_keys = [
        "tip_admin", "tip_theme", "tip_ctrlc", "tip_startup",
        "tip_cleantemp", "tip_security", "tip_speedtest", "tip_privacy",
    ]
    return [lang(k) for k in tip_keys]


def get_greeting_text():
    """Get time-based greeting in current language."""
    import datetime
    hour = datetime.datetime.now().hour
    if 5 <= hour < 12:
        return lang("good_morning")
    elif 12 <= hour < 15:
        return lang("good_afternoon")
    elif 15 <= hour < 18:
        return lang("good_evening")
    else:
        return lang("good_night")


def get_category_name(cat_key):
    """Get translated category name.
    
    Args:
        cat_key: Category key (e.g., 'cat_power', 'cat_info', etc.)
    
    Returns:
        Translated category name string.
    """
    return lang(cat_key)